import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {CalendarSearch,MessageCircle,Star} from 'lucide-react';
import {base44} from '@/api/base44Client';
import ExtraContactForm from '@/components/extras/ExtraContactForm';

export default function RhExtraAvailabilityPanel(){
  const[date,setDate]=useState('');const[role,setRole]=useState('');const[jobs,setJobs]=useState([]);const[items,setItems]=useState([]);const[loading,setLoading]=useState(false);const[contact,setContact]=useState(null);
  useEffect(()=>{base44.entities.ExtraJobType.filter({active:true},'display_order',100).then(setJobs)},[]);
  useEffect(()=>{if(!date||!role){setItems([]);return}setLoading(true);base44.functions.invoke('staffHub',{action:'available_regular_extras',event_date:date,role}).then(r=>setItems(r.data.items||[])).finally(()=>setLoading(false))},[date,role]);
  const send=form=>base44.functions.invoke('extrasHub',{action:'contact',data:form});
  return <section className="rounded-3xl border bg-card p-5 shadow-lg"><div className="flex items-center gap-2"><CalendarSearch className="text-primary"/><h2 className="text-xl font-bold">Extras disponibles pour une mission</h2></div><p className="mt-1 text-sm text-muted-foreground">La sélection se met à jour automatiquement selon la date et le métier.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label><label className="text-sm font-bold">Métier<select value={role} onChange={e=>setRole(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="">Choisir</option>{jobs.map(job=><option key={job.id} value={job.name}>{job.name}</option>)}</select></label></div>{loading?<div className="mt-4 h-24 animate-pulse rounded-2xl bg-muted"/>:date&&role?<div className="mt-4 grid gap-3 md:grid-cols-2">{items.map(extra=><article key={extra.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-bold">{extra.first_name} {extra.last_name}</h3><p className="text-sm text-muted-foreground">{extra.city} · {extra.experience_years} an(s)</p></div>{extra.regular&&<span className="flex items-center gap-1 rounded-full bg-secondary px-2 py-1 text-xs font-bold"><Star size={13}/>Régulier</span>}</div><div className="mt-3 flex gap-2"><Link to={`/extras-pro?extra=${extra.id}`} className="rounded-xl border px-3 py-2 text-sm font-bold">Voir fiche et planning</Link><button type="button" onClick={()=>setContact(extra)} className="flex items-center gap-1 rounded-xl bg-primary px-3 py-2 text-sm font-bold text-primary-foreground"><MessageCircle size={15}/>Contacter</button></div>{contact?.id===extra.id&&<ExtraContactForm extra={extra} onSubmit={send} onClose={()=>setContact(null)}/>}</article>)}{!items.length&&<p className="rounded-2xl border border-dashed p-5 text-sm text-muted-foreground md:col-span-2">Aucun Extra disponible pour cette date et ce métier.</p>}</div>:null}</section>;
}