import {useState} from 'react';
import {Building2,CalendarDays,Check,Mail,MapPin,Phone,X} from 'lucide-react';
import {formatAvailabilityDate} from '@/lib/extraAvailability';
const labels={pending:'En attente de votre validation',confirmed:'Réservation confirmée'};
export default function BlockedDateDetails({booking,onClose,onConfirm}){
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');if(!booking)return null;
  const confirm=async()=>{setBusy(true);setError('');try{await onConfirm(booking,'confirmed');onClose()}catch(err){setError(err.response?.data?.error||err.message)}finally{setBusy(false)}};
  const mailSubject=encodeURIComponent(`Informations sur la demande du ${formatAvailabilityDate(booking.booking_date)}`);const mailBody=encodeURIComponent(`Bonjour,\n\nJe souhaite obtenir des informations complémentaires concernant la prestation prévue le ${formatAvailabilityDate(booking.booking_date)}.\n\nMerci.`);
  return <div className="fixed inset-0 z-[1100] grid place-items-center bg-foreground/50 p-4" role="dialog" aria-modal="true" aria-labelledby="blocked-date-title" onClick={onClose}><div className="w-full max-w-md rounded-3xl border bg-card p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><p className={`text-xs font-bold uppercase tracking-widest ${booking.status==='pending'?'text-chart-5':'text-destructive'}`}>Créneau réservé</p><h3 id="blocked-date-title" className="mt-1 text-xl font-bold">{labels[booking.status]}</h3></div><button type="button" onClick={onClose} aria-label="Fermer" className="rounded-full p-2 hover:bg-secondary"><X size={20}/></button></div><div className="mt-5 space-y-3 text-sm"><p className="flex items-center gap-2"><CalendarDays size={17}/><b>{formatAvailabilityDate(booking.booking_date)}</b></p><p className="flex items-center gap-2"><Building2 size={17}/>{booking.caterer_name||'Traiteur non renseigné'}</p><p className="flex items-start gap-2"><MapPin size={17} className="mt-0.5 shrink-0"/>{booking.location||booking.caterer_address||booking.caterer_city||'Lieu non renseigné'}</p><p><b>Prestation :</b> {booking.service_details||'Non renseignée'}</p>{booking.status==='confirmed'&&<div className="space-y-2 rounded-2xl bg-secondary/50 p-3"><p><b>Contact confirmé</b></p><a href={`tel:${booking.caterer_phone||''}`} className="flex items-center gap-2"><Phone size={15}/>{booking.caterer_phone||'Téléphone non renseigné'}</a><a href={`mailto:${booking.caterer_email||''}`} className="flex items-center gap-2"><Mail size={15}/>{booking.caterer_email||'E-mail non renseigné'}</a></div>}</div>{error&&<p className="mt-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="mt-5 grid gap-2 sm:grid-cols-2">{booking.status==='pending'&&booking.initiated_by!=='extra'&&<button type="button" onClick={confirm} disabled={busy} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-bold text-primary-foreground disabled:opacity-50"><Check size={18}/>{busy?'Validation…':'Valider'}</button>}<a href={`mailto:${booking.caterer_email||''}?subject=${mailSubject}&body=${mailBody}`} className="flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-center font-bold"><Mail size={18}/>Demander des infos</a></div><button type="button" onClick={onClose} className="mt-2 w-full rounded-xl bg-secondary px-4 py-3 font-bold text-primary">Fermer</button></div></div>;
}