import {useEffect,useState} from 'react';
import {CheckCheck,MessageCircle,Send} from 'lucide-react';
import {base44} from '@/api/base44Client';
import CatererTrustCard from '@/components/extras/CatererTrustCard';
export default function BookingMessenger({booking,viewerRole,open=true}){
  const[context,setContext]=useState(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  useEffect(()=>{const load=()=>base44.functions.invoke('extrasHub',{action:'booking_context',booking_id:booking.id}).then(response=>setContext(response.data)).catch(err=>setError(err.response?.data?.error||err.message));load();const unsubscribe=base44.entities.ExtraBookingMessage.subscribe(event=>{if(event.data?.booking_id===booking.id)load()});return unsubscribe},[booking.id]);
  const send=async()=>{setBusy(true);setError('');try{const response=await base44.functions.invoke('extrasHub',{action:'send_booking_message',booking_id:booking.id,message});setContext(current=>({...current,messages:[...(current?.messages||[]),response.data.item]}));setMessage('')}catch(err){setError(err.response?.data?.error||err.message)}finally{setBusy(false)}};
  if(!context&&!error)return <div className="mt-4 h-20 animate-pulse rounded-2xl bg-muted"/>;
  return <div className="mt-4 space-y-3 border-t pt-4">{viewerRole==='extra'&&context&&<CatererTrustCard booking={booking} context={context} onRated={data=>setContext(current=>({...current,...data,own_review:data.item}))}/>} {open&&<div><p className="flex items-center gap-2 font-bold"><MessageCircle size={17}/>Messagerie interne</p><div className="mt-2 max-h-44 space-y-2 overflow-y-auto rounded-2xl bg-muted/50 p-3">{context?.messages?.length?context.messages.map(item=><div key={item.id} className={`rounded-xl p-2 text-sm ${item.sender_role===viewerRole?'ml-6 bg-primary text-primary-foreground':'mr-6 bg-card'}`}><b>{item.sender_name}</b><p>{item.message}</p>{item.sender_role===viewerRole&&item.read_at&&<small className="mt-1 flex items-center justify-end gap-1 opacity-75"><CheckCheck size={13}/>Lu</small>}</div>):<p className="text-sm text-muted-foreground">Aucun message pour cette demande.</p>}</div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Écrivez votre message…" className="mt-2 min-h-20 w-full rounded-xl border p-3"/><button type="button" onClick={send} disabled={message.trim().length<2||busy} className="mt-2 flex items-center gap-2 rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground disabled:opacity-50"><Send size={16}/>{busy?'Envoi…':'Envoyer et notifier par e-mail'}</button>{error&&<p className="mt-2 text-sm text-destructive">{error}</p>}</div>}</div>;
}