import {useState} from 'react';
import {base44} from '@/api/base44Client';
import ExtraIdentityFields from '@/components/extras/ExtraIdentityFields';
import ExtraWorkFields from '@/components/extras/ExtraWorkFields';
import ExtraPrivacyFields from '@/components/extras/ExtraPrivacyFields';
import ExtraLocationField from '@/components/extras/ExtraLocationField';

const defaults={first_name:'',last_name:'',email:'',phone:'',date_of_birth:'',gender:'',address:'',postal_code:'',city:'',latitude:null,longitude:null,skills:[],experience_years:'',experience_details:'',clothing_size:'',height_cm:'',languages:[],certifications:[],availability_notes:'',availability_dates:[],availability_slots:[],availability_period:'day',mobility_radius_km:'',transport:[],hourly_rate:'',photo_urls:[],available:true,display_last_name:false,display_email:false,display_phone:false,contact_preference:'site'};
export default function ExtraProfileForm({initial,user,bookings=[],onSaved}) {
  const [data,setData]=useState(()=>{const transport=initial?.transport==='both'?['public','vehicle']:Array.isArray(initial?.transport)?initial.transport:initial?.transport?[initial.transport]:[];return {...defaults,email:user?.email||'',...initial,transport}}); const [busy,setBusy]=useState(false); const [files,setFiles]=useState([]); const [error,setError]=useState('');
  const set=(key,list=false)=>e=>setData(x=>({...x,[key]:list?e.target.value.split(',').map(v=>v.trim()).filter(Boolean):e.target.type==='checkbox'?e.target.checked:e.target.value}));
  const toggleSkill=skill=>setData(x=>({...x,skills:(x.skills||[]).includes(skill)?x.skills.filter(item=>item!==skill):[...(x.skills||[]),skill]}));
  const toggleArray=(key,value)=>setData(x=>{const current=Array.isArray(x[key])?x[key]:[];let next=current.includes(value)?current.filter(item=>item!==value):[...current,value];if(key==='transport')next=value==='none'?['none']:next.filter(item=>item!=='none');return {...x,[key]:next}});
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const uploads=await Promise.all([...files].map(file=>base44.integrations.Core.UploadFile({file})));const number=value=>value===''?undefined:Number(value);const payload={...data,experience_years:number(data.experience_years),height_cm:number(data.height_cm),mobility_radius_km:number(data.mobility_radius_km),hourly_rate:number(data.hourly_rate),photo_urls:[...(data.photo_urls||[]),...uploads.map(item=>item.file_url)],status:'pending',admin_comment:'',active:true};const response=await base44.functions.invoke('extrasHub',{action:'save_profile',data:payload});onSaved(response.data.item)}catch(err){setError(err.message||'Enregistrement impossible.')}finally{setBusy(false)}};
  return <form onSubmit={submit} className="space-y-5 text-sm font-semibold">
    <ExtraIdentityFields data={data} set={set} toggleSkill={toggleSkill}/>
    <section id="coordonnees" className="scroll-mt-24"><h2 className="mb-3 text-lg font-bold">Coordonnées privées</h2><div className="grid gap-4 sm:grid-cols-[1fr_130px]"><label>Adresse *<input required autoComplete="street-address" value={data.address||''} onChange={set('address')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label><label>Code postal *<input required autoComplete="postal-code" value={data.postal_code||''} onChange={set('postal_code')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label><div className="sm:col-span-2"><ExtraLocationField cityOnly label="Ville *" value={data.city||''} onChange={city=>setData(x=>({...x,city,latitude:null,longitude:null}))} onSelect={place=>setData(x=>({...x,city:place.location,latitude:place.latitude,longitude:place.longitude}))}/></div></div></section>
    <ExtraWorkFields data={data} set={set} toggleArray={toggleArray}/><ExtraPrivacyFields data={data} set={set}/>
    <label className="block">Photos <span className="font-normal text-muted-foreground">(facultatives)</span><input type="file" multiple accept="image/*" onChange={e=>setFiles(e.target.files)} className="mt-1 block w-full rounded-xl border bg-background p-3"/></label>
    <label className="flex gap-3 rounded-xl bg-secondary p-3"><input type="checkbox" checked={Boolean(data.available)} onChange={set('available')}/>Je suis actuellement disponible</label>
    {error&&<p className="rounded-xl bg-destructive/10 p-3 text-destructive">{error}</p>}<button disabled={busy} className="sticky bottom-3 z-20 w-full rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground shadow-2xl disabled:opacity-50">{busy?'Enregistrement…':initial?'Enregistrer mes modifications':'Soumettre mon profil à validation'}</button>
  </form>;
}