import {Crosshair,Search} from 'lucide-react';
import ExtraLocationField from '@/components/extras/ExtraLocationField';

export default function ExtraOpportunityFilters({value,onChange,onSubmit,locating,onLocate,roles=[]}){
  const set=(key,next)=>onChange({...value,[key]:next});
  return <form onSubmit={e=>{e.preventDefault();onSubmit()}} className="rounded-2xl border bg-card/90 p-4 shadow-lg backdrop-blur-xl">
    <h2 className="font-bold">Autour de moi</h2><p className="mt-1 text-xs text-muted-foreground">Choisissez une ville et votre rayon de recherche.</p>
    <div className="mt-4 space-y-3 text-sm"><div className="relative"><ExtraLocationField cityOnly label="Ville" required={false} value={value.city} onChange={city=>onChange({...value,city,latitude:null,longitude:null})} onSelect={place=>onChange({...value,city:place.location,latitude:place.latitude,longitude:place.longitude})}/><button type="button" onClick={onLocate} disabled={locating} className="absolute right-2 top-7 rounded-lg bg-secondary p-2 text-primary" aria-label="Utiliser ma position"><Crosshair size={16}/></button></div><label className="block">Rayon<select value={value.radius_km} onChange={e=>set('radius_km',Number(e.target.value))} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="10">10 km</option><option value="25">25 km</option><option value="50">50 km</option><option value="75">75 km</option><option value="100">100 km</option></select></label><label className="block">Métier<select value={value.role} onChange={e=>set('role',e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="">Tous les métiers</option>{roles.map(role=><option key={role} value={role}>{role}</option>)}</select></label><label className="block">Jour<input type="date" value={value.date} onChange={e=>set('date',e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label></div>
    <button type="submit" className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-bold text-primary-foreground"><Search size={16}/>Afficher les annonces</button>
  </form>;
}