import {formatAvailabilityDate,getAvailabilityPreset,getAvailabilityWindow,sanitizeAvailabilitySlots} from '@/lib/extraAvailability';
const modes=[['day','Journée','bg-chart-4 text-primary'],['evening','Soirée','bg-destructive text-destructive-foreground'],['both','Journée + soirée','bg-chart-2 text-primary-foreground']];
const presets=[['weekends','Tous les week-ends'],['weekdays','Jours de semaine'],['month','Tout le mois']];
const slotClass={day:'border-chart-4 bg-chart-4 text-primary',evening:'border-destructive bg-destructive text-destructive-foreground',both:'border-chart-2 bg-chart-2 text-primary-foreground'};
export default function ExtraAvailabilityCalendar({value,onChange,mode,onModeChange}) {
  const dates=getAvailabilityWindow(); const slots=sanitizeAvailabilitySlots(value); const byDate=new Map(slots.map(slot=>[slot.date,slot.period]));
  const toggleDate=date=>onChange(byDate.get(date)===mode?slots.filter(slot=>slot.date!==date):[...slots.filter(slot=>slot.date!==date),{date,period:mode}].sort((a,b)=>a.date.localeCompare(b.date)));
  const togglePreset=preset=>{const target=getAvailabilityPreset(preset);const remove=target.every(date=>byDate.get(date)===mode);onChange(remove?slots.filter(slot=>!target.includes(slot.date)):[...slots.filter(slot=>!target.includes(slot.date)),...target.map(date=>({date,period:mode}))].sort((a,b)=>a.date.localeCompare(b.date)))};
  return <section id="disponibilites" className="scroll-mt-24 rounded-3xl border bg-secondary/30 p-4 shadow-sm sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-destructive">Accès rapide</p><h2 className="mt-1 text-xl font-bold">Mes disponibilités</h2></div><button type="button" onClick={()=>onChange([])} disabled={!slots.length} className="rounded-xl border bg-card px-3 py-2 text-xs font-bold disabled:opacity-40">Remettre à zéro</button></div><p className="mt-2 font-normal text-muted-foreground">Choisissez un type, puis touchez les jours. Touchez à nouveau un choix pour le retirer.</p><div className="mt-4 grid grid-cols-3 gap-2">{modes.map(([key,label,color])=><button type="button" key={key} aria-pressed={mode===key} onClick={()=>onModeChange(key)} className={`rounded-xl border-2 px-2 py-3 text-xs font-bold ${mode===key?color:'border-border bg-card text-foreground'}`}>{label}</button>)}</div><div className="mt-3 flex flex-wrap gap-2">{presets.map(([key,label])=><button type="button" key={key} onClick={()=>togglePreset(key)} className="rounded-xl border bg-card px-3 py-2 text-xs font-bold hover:bg-primary hover:text-primary-foreground">{label}</button>)}</div><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-5">{dates.map(date=>{const period=byDate.get(date);const weekend=[0,6].includes(new Date(`${date}T12:00:00`).getDay());return <button type="button" key={date} onClick={()=>toggleDate(date)} className={`relative rounded-xl border px-2 py-3 text-xs capitalize ${period?slotClass[period]:(weekend?'border-primary/40 bg-card':'bg-card hover:bg-secondary')}`}>{weekend&&<span className="absolute right-1 top-1 text-[8px] font-black opacity-70">WE</span>}{formatAvailabilityDate(date)}</button>})}</div><p className="mt-3 text-xs font-normal text-muted-foreground">{slots.length} jour{slots.length!==1?'s':''} renseigné{slots.length!==1?'s':''}</p></section>;
}