import {useMemo,useState} from 'react';
import {formatAvailabilityDate,getAvailabilityWindow} from '@/lib/extraAvailability';

const legend=[['bg-destructive text-destructive-foreground','Bloqué'],['bg-chart-2 text-primary-foreground','Disponible'],['bg-chart-5 text-primary','En attente'],['bg-sidebar-ring text-primary-foreground','Disponible en semaine'],['bg-foreground text-background','Disponible le soir'],['bg-muted text-muted-foreground','Soir et week-end']];
const availableClass=(date,period)=>{const weekend=[0,6].includes(new Date(`${date}T12:00:00`).getDay());if(period==='evening')return weekend?'bg-muted text-muted-foreground':'bg-foreground text-background';if(period==='day'&&!weekend)return'bg-sidebar-ring text-primary-foreground';return'bg-chart-2 text-primary-foreground'};
export default function ExtraBookingCalendar({extra,onSubmit,onClose}){
  const[selected,setSelected]=useState([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const dates=getAvailabilityWindow();
  const slots=useMemo(()=>new Map((extra.availability_slots||[]).map(x=>[x.date,x.period])),[extra]);const bookings=useMemo(()=>new Map((extra.booking_days||[]).map(x=>[x.booking_date,x.status])),[extra]);
  const toggle=date=>{if(!slots.has(date)||bookings.has(date))return;setSelected(x=>x.includes(date)?x.filter(d=>d!==date):[...x,date])};
  const submit=async()=>{setBusy(true);setError('');try{await onSubmit({extra_id:extra.id,dates:selected});onClose()}catch(err){setError(err.response?.data?.error||err.message||'Réservation impossible.')}finally{setBusy(false)}};
  return <div className="border-t bg-secondary/20 p-5"><h3 className="font-bold">Choisir les jours à réserver</h3><div className="mt-3 flex flex-wrap gap-2">{legend.map(([color,label])=><span key={label} className={`rounded-full px-3 py-1 text-xs font-bold ${color}`}>{label}</span>)}</div><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-5">{dates.map(date=>{const period=slots.get(date);const status=bookings.get(date);const color=status==='confirmed'?'bg-destructive text-destructive-foreground':status==='pending'?'bg-chart-5 text-primary':period?availableClass(date,period):'bg-card text-muted-foreground opacity-45';return <button type="button" key={date} disabled={!period||Boolean(status)} onClick={()=>toggle(date)} className={`rounded-xl border px-2 py-3 text-xs capitalize ${selected.includes(date)?'ring-4 ring-primary':color}`}>{formatAvailabilityDate(date)}</button>})}</div>{error&&<p className="mt-3 rounded-xl bg-destructive/10 p-3 text-sm font-semibold text-destructive">{error}</p>}<div className="mt-4 flex gap-2"><button type="button" disabled={!selected.length||busy} onClick={submit} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground disabled:opacity-40">{busy?'Envoi…':`Réserver ${selected.length} jour(s)`}</button><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2 text-sm font-bold">Fermer</button></div></div>;
}