import {useState} from 'react';
import {CircleMarker,Popup} from 'react-leaflet';
import {BriefcaseBusiness,CalendarDays,MapPin} from 'lucide-react';
import {Image} from '@/components/ui/image';
import {formatAvailabilityDate} from '@/lib/extraAvailability';

export default function ExtraOpportunityMarker({item,onView,onApply}){
  const[details,setDetails]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const applied=['pending','confirmed'].includes(item.application_status);const view=async()=>{if(!details)await onView(item);setDetails(value=>!value)};const apply=async()=>{setBusy(true);setError('');try{await onApply(item)}catch(e){setError(e.response?.data?.error||e.message)}finally{setBusy(false)}};
  return <CircleMarker center={[item.latitude,item.longitude]} radius={10} pathOptions={{color:'hsl(var(--primary))',fillColor:'hsl(var(--destructive))',fillOpacity:1,weight:4}}><Popup><article className="w-64 p-1"><div className="flex items-center gap-3">{item.caterer_logo_url?<Image src={item.caterer_logo_url} alt={`Logo ${item.caterer_name}`} fittingType="fit" className="h-12 w-12 rounded-xl border bg-card"/>:<span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-secondary text-lg font-bold text-primary">{item.caterer_name?.[0]||'T'}</span>}<div><p className="text-xs font-bold uppercase tracking-wide text-destructive">{item.caterer_name}</p><h3 className="mt-1 flex items-center gap-1 text-base font-bold"><BriefcaseBusiness size={15}/>{item.role}</h3></div></div><p className="mt-3 flex items-center gap-2 text-sm"><CalendarDays size={15}/>{formatAvailabilityDate(item.event_date)}</p><p className="mt-1 flex items-center gap-2 text-sm"><MapPin size={15}/>{item.location}</p>{details&&<div className="mt-3 border-t pt-3 text-sm"><p>{item.description}</p>{item.hourly_rate&&<p className="mt-2 font-bold">{item.hourly_rate} € / heure</p>}</div>}{error&&<p className="mt-2 text-xs font-semibold text-destructive">{error}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={view} className="rounded-xl border px-3 py-2 text-sm font-bold">{details?'Masquer':'Voir'}</button><button type="button" onClick={apply} disabled={busy||applied} className="rounded-xl bg-primary px-3 py-2 text-sm font-bold text-primary-foreground disabled:opacity-50">{applied?'Envoyée':busy?'Envoi…':'Postuler'}</button></div></article></Popup></CircleMarker>;
}