import {useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import RequestGeolocationField from '@/components/extras/RequestGeolocationField';

const initial={role:'',event_date:'',start_time:'',end_time:'',location:'',latitude:null,longitude:null,radius_km:15,required_count:1,hourly_rate:'',description:''};
export default function ExtraRequestForm({onSubmit,request,onCancel}){
  const[data,setData]=useState(initial);const[jobs,setJobs]=useState([]);const[busy,setBusy]=useState(false);
  useEffect(()=>{base44.entities.ExtraJobType.filter({active:true},'display_order',100).then(setJobs)},[]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setData(request?{...initial,...request,radius_km:request.radius_km||15}:{...initial,role:params.get('role')||'',event_date:params.get('date')||'',location:params.get('location')||'',required_count:Number(params.get('count')||1),description:params.get('description')||''})},[request]);
  const set=key=>e=>setData(x=>({...x,[key]:e.target.value}));const submit=async e=>{e.preventDefault();setBusy(true);await onSubmit(data);setData(initial);window.history.replaceState({},'',window.location.pathname);setBusy(false)};
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label>Profil recherché<select required value={data.role} onChange={set('role')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="">Choisir un métier</option>{jobs.map(job=><option key={job.id} value={job.name}>{job.name}</option>)}</select></label><label>Date<input required type="date" value={data.event_date} onChange={set('event_date')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label><label>Début<input type="time" value={data.start_time} onChange={set('start_time')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label><label>Fin<input type="time" value={data.end_time} onChange={set('end_time')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label><label>Nombre d’extras<input min="1" type="number" value={data.required_count} onChange={set('required_count')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label><label>Taux horaire indicatif (€)<input min="0" type="number" value={data.hourly_rate} onChange={set('hourly_rate')} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"/></label></div><RequestGeolocationField data={data} onChange={location=>setData(x=>({...x,location,latitude:null,longitude:null}))} onSelect={place=>setData(x=>({...x,...place}))}/><label className="block">Détails de la mission<textarea required value={data.description} onChange={set('description')} className="mt-1 min-h-24 w-full rounded-xl border bg-background p-3"/></label><div className="flex gap-2">{request&&<button type="button" onClick={onCancel} className="flex-1 rounded-xl border px-5 py-3 font-bold">Annuler</button>}<button disabled={busy} className="flex-1 rounded-xl bg-destructive px-5 py-3 font-bold text-destructive-foreground">{busy?'Enregistrement…':request?'Enregistrer':'Publier la demande'}</button></div></form>;
}