import {useState} from 'react';
import {Mail,MapPin,Phone,Star} from 'lucide-react';
import {Image} from '@/components/ui/image';
import ExtraRatingForm from '@/components/extras/ExtraRatingForm';
import ExtraContactForm from '@/components/extras/ExtraContactForm';
import ExtraAvailabilitySummary from '@/components/extras/ExtraAvailabilitySummary';
import ExtraBookingCalendar from '@/components/extras/ExtraBookingCalendar';

export default function ExtraCard({extra,onBook,onRecommend,onContact}) {
  const [rating,setRating]=useState(false); const [contact,setContact]=useState(false); const [calendar,setCalendar]=useState(false); const name=[extra.first_name||'Extra',extra.last_name].filter(Boolean).join(' ');
  return <article className="overflow-hidden rounded-3xl border bg-card shadow-sm"><div className="grid grid-cols-[96px_1fr] gap-4 p-5">{extra.photo_urls?.[0]?<Image src={extra.photo_urls[0]} alt={name} className="h-24 w-24 rounded-2xl"/>:<div className="grid h-24 w-24 place-items-center rounded-2xl bg-secondary text-2xl font-bold text-primary">{extra.first_name?.[0]||'E'}{extra.last_name?.[0]||''}</div>}<div><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-lg font-bold">{name}</h2><p className="text-sm text-muted-foreground">{extra.age?`${extra.age} ans · `:''}{extra.experience_years?`${extra.experience_years} ans d’expérience`:'Expérience non renseignée'}</p></div><span className="flex items-center gap-1 rounded-full bg-secondary px-3 py-1 text-sm font-bold"><Star size={15} className="fill-current"/>{extra.average_rating?extra.average_rating.toFixed(1):'Nouveau'}</span></div>{extra.city&&<p className="mt-2 flex items-center gap-1 text-sm"><MapPin size={15}/>{extra.city}{extra.postal_code?` (${extra.postal_code})`:''}</p>}<div className="mt-2 flex flex-wrap gap-1">{(extra.skills||[]).map(skill=><span key={skill} className="rounded-full border px-2 py-1 text-xs">{skill}</span>)}</div></div></div>
    <div className="border-t px-5 py-4 text-sm">{extra.experience_details&&<p>{extra.experience_details}</p>}<ExtraAvailabilitySummary dates={extra.availability_dates} slots={extra.availability_slots}/><div className="mt-3 flex flex-wrap gap-3">{extra.email&&<a href={`mailto:${extra.email}`} className="flex items-center gap-1 font-semibold text-primary underline"><Mail size={15}/>{extra.email}</a>}{extra.phone&&<a href={`tel:${extra.phone}`} className="flex items-center gap-1 font-semibold text-primary underline"><Phone size={15}/>{extra.phone}</a>}</div>{extra.recommendations?.map((item,index)=><blockquote key={index} className="mt-3 border-l-2 border-primary pl-3 text-muted-foreground">“{item.comment}” — {item.caterer_name}, {item.rating}/5</blockquote>)}
      <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setCalendar(true)} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Voir le calendrier</button><button onClick={()=>setContact(true)} className="rounded-xl border px-4 py-2 font-bold text-primary">Contacter via le site</button><button onClick={()=>setRating(true)} className="rounded-xl border px-4 py-2 font-bold text-primary">Laisser une recommandation</button></div>{contact&&<ExtraContactForm extra={extra} onSubmit={onContact} onClose={()=>setContact(false)}/>} {rating&&<ExtraRatingForm extra={extra} onSubmit={onRecommend} onClose={()=>setRating(false)}/>}</div>{calendar&&<ExtraBookingCalendar extra={extra} onSubmit={onBook} onClose={()=>setCalendar(false)}/>}</article>;
}