import {useMemo,useState} from 'react';
import ExtraBookingMonth from '@/components/extras/ExtraBookingMonth';
import ExtraBookingFormDialog from '@/components/extras/ExtraBookingFormDialog';

const legend=[['bg-destructive text-destructive-foreground','Confirmé'],['bg-chart-5 text-primary','En attente'],['bg-chart-2 text-primary-foreground','Disponible'],['bg-sidebar-ring text-primary-foreground','Journée'],['bg-foreground text-background','Soirée']];
export default function ExtraBookingCalendar({extra,onSubmit,onClose}){
  const[monthOffset,setMonthOffset]=useState(0);const[selectedDate,setSelectedDate]=useState(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const slots=useMemo(()=>new Map((extra.availability_slots||[]).map(item=>[item.date,item.period])),[extra.availability_slots]);const bookings=useMemo(()=>new Map((extra.booking_days||[]).map(item=>[item.booking_date,item.status])),[extra.booking_days]);
  const submit=async({date,job,location,message})=>{setBusy(true);setError('');try{const details=`Prestation prévue : ${job}${message?`\nMessage : ${message}`:''}`;await onSubmit({extra_id:extra.id,dates:[date],location,service_details:details});onClose()}catch(err){setError(err.response?.data?.error||err.message||'Réservation impossible.')}finally{setBusy(false)}};
  return <div className="border-t bg-secondary/20 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Calendrier des disponibilités</h3><p className="mt-1 text-sm text-muted-foreground">Cliquez sur un jour disponible pour prévoir une prestation.</p></div><button type="button" onClick={onClose} className="rounded-xl border bg-card px-3 py-2 text-sm font-bold">Fermer</button></div><div className="mt-3 flex flex-wrap gap-2">{legend.map(([color,label])=><span key={label} className={`rounded-full px-3 py-1 text-xs font-bold ${color}`}>{label}</span>)}</div><ExtraBookingMonth monthOffset={monthOffset} slots={slots} bookings={bookings} onMonth={setMonthOffset} onSelect={date=>{setError('');setSelectedDate(date)}}/><ExtraBookingFormDialog key={selectedDate} date={selectedDate} extra={extra} busy={busy} error={error} onSubmit={submit} onClose={()=>setSelectedDate(null)}/></div>;
}