import {useEffect,useMemo,useState} from 'react';
import {Grid2X2,Map as MapIcon} from 'lucide-react';
import {base44} from '@/api/base44Client';
import ExtraCard from '@/components/extras/ExtraCard';
import ExtraDirectoryLocationFilter from '@/components/extras/ExtraDirectoryLocationFilter';
import ProExtraDirectoryMap from '@/components/extras/ProExtraDirectoryMap';
import {getAvailabilityWindow} from '@/lib/extraAvailability';
import {distanceKm} from '@/lib/distance';

export default function ProExtraSearchPanel({items,onBook,onRecommend,onContact,onView}){
  const params=new URLSearchParams(window.location.search);const[displayMode,setDisplayMode]=useState('grid');const[jobs,setJobs]=useState([]);const[search,setSearch]=useState('');const[skill,setSkill]=useState(params.get('skill')||'');const[gender,setGender]=useState('');const[date,setDate]=useState(params.get('date')||'');const[origin,setOrigin]=useState(null);const[radius,setRadius]=useState(15);const availabilityWindow=getAvailabilityWindow();
  useEffect(()=>{base44.entities.ExtraJobType.filter({active:true},'display_order',100).then(setJobs)},[]);
  const filtered=useMemo(()=>items.filter(item=>(!skill||(item.skills||[]).includes(skill))&&(!gender||item.gender===gender)&&(!date||((item.availability_dates||[]).includes(date)||(item.availability_slots||[]).some(slot=>slot.date===date)))&&(!search||`${item.first_name||''} ${item.last_name||''} ${item.city||''}`.toLowerCase().includes(search.toLowerCase()))&&(!origin||(item.latitude!=null&&item.longitude!=null&&distanceKm(origin,{latitude:item.latitude,longitude:item.longitude})<=radius))),[items,search,skill,gender,date,origin,radius]);
  return <section className="mt-7"><div className="rounded-3xl border bg-card p-5 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-destructive">Recherche</p><h2 className="mt-1 text-2xl font-bold">Trouver un Extra</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_220px_170px_180px]"><input value={search} onChange={e=>setSearch(e.target.value)} className="h-11 rounded-xl border bg-background px-3" placeholder="Prénom ou ville"/><select value={skill} onChange={e=>setSkill(e.target.value)} className="h-11 rounded-xl border bg-background px-3"><option value="">Tous les métiers</option>{jobs.map(job=><option key={job.id} value={job.name}>{job.name}</option>)}</select><select value={gender} onChange={e=>setGender(e.target.value)} className="h-11 rounded-xl border bg-background px-3"><option value="">Tous les genres</option><option value="femme">Femme</option><option value="homme">Homme</option><option value="autre">Autre</option></select><input type="date" aria-label="Disponibilité le" min={availabilityWindow[0]} max={availabilityWindow[29]} value={date} onChange={e=>setDate(e.target.value)} className="h-11 rounded-xl border bg-background px-3"/></div><ExtraDirectoryLocationFilter active={Boolean(origin)} radius={radius} onLocate={setOrigin} onRadius={setRadius} onClear={()=>setOrigin(null)}/><div className="mt-4 flex w-fit gap-1 rounded-xl bg-secondary p-1"><button type="button" onClick={()=>setDisplayMode('grid')} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${displayMode==='grid'?'bg-card text-primary shadow-sm':'text-muted-foreground'}`}><Grid2X2 size={16}/>Grille</button><button type="button" onClick={()=>setDisplayMode('map')} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${displayMode==='map'?'bg-card text-primary shadow-sm':'text-muted-foreground'}`}><MapIcon size={16}/>Carte</button></div></div><p className="my-4 text-sm font-semibold text-muted-foreground">{filtered.length} profil(s) disponible(s)</p>{displayMode==='grid'?<div className="grid gap-5 lg:grid-cols-2">{filtered.map(extra=><ExtraCard key={extra.id} extra={extra} onBook={onBook} onRecommend={onRecommend} onContact={onContact} onView={onView}/>)}</div>:<ProExtraDirectoryMap items={filtered}/>}</section>;
}