import {useState} from 'react';
import {History,MessageCircle,Star,Users} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Image} from '@/components/ui/image';
import ExtraAvailabilitySummary from '@/components/extras/ExtraAvailabilitySummary';
import ExtraContactForm from '@/components/extras/ExtraContactForm';

export default function RegularExtraList({items=[],profiles=[],onContact}){
  const[contact,setContact]=useState(null);const byId=new Map(profiles.map(profile=>[profile.id,profile]));const extras=Object.values(items.filter(x=>x.extra_profile_id&&x.status==='confirmed').reduce((all,item)=>{const current=all[item.extra_profile_id]||{id:item.extra_profile_id,name:item.extra_name||'Extra',photo:item.extra_photo_url,missions:[]};current.missions.push(item);all[item.extra_profile_id]=current;return all},{})).sort((a,b)=>b.missions.length-a.missions.length);
  return <section className="mt-6 rounded-3xl border bg-card p-5 shadow-lg"><div className="flex items-center gap-2"><Users className="text-primary"/><h2 className="text-xl font-bold">Mes Extras réguliers</h2></div><p className="mt-1 text-sm text-muted-foreground">Consultez leur planning, ouvrez leur fiche ou contactez-les pour une nouvelle mission.</p>{extras.length?<div className="mt-4 grid gap-4 md:grid-cols-2">{extras.map(extra=>{const profile=byId.get(extra.id)||extra;const missions=[...extra.missions].sort((a,b)=>String(b.booking_date).localeCompare(String(a.booking_date)));return <article key={extra.id} className="rounded-2xl border p-4"><div className="flex items-center gap-3">{extra.photo?<Image src={extra.photo} alt="" className="h-11 w-11 rounded-full"/>:<span className="grid h-11 w-11 place-items-center rounded-full bg-secondary font-bold">{extra.name.charAt(0)}</span>}<div><h3 className="font-bold">{extra.name}</h3><p className="flex items-center gap-1 text-xs text-muted-foreground">{missions.length>=2&&<Star size={13} className="text-chart-4"/>}{missions.length} mission(s) confirmée(s)</p></div></div><ExtraAvailabilitySummary dates={profile.availability_dates} slots={profile.availability_slots}/><p className="mt-3 flex items-center gap-1 text-xs font-bold"><History size={13}/>Dernière mission · {new Date(`${missions[0].booking_date}T12:00:00`).toLocaleDateString('fr-FR')}</p><div className="mt-3 flex gap-2"><Link to={`/extras-pro?extra=${extra.id}`} className="rounded-xl border px-3 py-2 text-sm font-bold">Fiche et planning</Link><button type="button" onClick={()=>setContact(profile)} className="flex items-center gap-1 rounded-xl bg-primary px-3 py-2 text-sm font-bold text-primary-foreground"><MessageCircle size={15}/>Contacter</button></div>{contact?.id===extra.id&&<ExtraContactForm extra={profile} onSubmit={onContact} onClose={()=>setContact(null)}/>}</article>})}</div>:<p className="mt-4 rounded-2xl border border-dashed p-6 text-center text-sm text-muted-foreground">Les Extras apparaîtront ici après leur première mission confirmée.</p>}</section>;
}