import {useState} from 'react';
import {FileSpreadsheet,Upload} from 'lucide-react';
import {base44} from '@/api/base44Client';
const slugify=value=>String(value||'traiteur').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const schema={type:'object',properties:{business_name:{type:'string'},city:{type:'string'},address:{type:'string'},postal_code:{type:'string'},contact_name:{type:'string'},email:{type:'string'},phone:{type:'string'},whatsapp_phone:{type:'string'},website:{type:'string'},siret:{type:'string'},description:{type:'string'},latitude:{type:'number'},longitude:{type:'number'}},required:['business_name','city']};
export default function AdminCatererImport({onImported}){
  const[file,setFile]=useState(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  const run=async()=>{if(!file)return;setBusy(true);setMessage('');try{const upload=await base44.integrations.Core.UploadFile({file});const extraction=await base44.integrations.Core.ExtractDataFromUploadedFile({file_url:upload.file_url,json_schema:schema});if(extraction.status!=='success')throw new Error(extraction.details||'Lecture du fichier impossible');const rows=Array.isArray(extraction.output)?extraction.output:(extraction.output?.items||[]);const stamp=Date.now().toString().slice(-7);const records=rows.filter(row=>row.business_name&&row.city).map((row,index)=>({...row,slug:`${slugify(row.business_name)}-${stamp}-${index+1}`,status:'approved',published:true,verified:false,demo:false,profile_origin:'public_source',claim_status:'unclaimed'}));if(!records.length)throw new Error('Aucun traiteur valide trouvé. Colonnes requises : business_name et city.');await base44.entities.CatererProfile.bulkCreate(records);setMessage(`${records.length} fiche(s) importée(s) et publiée(s).`);setFile(null);await onImported?.()}catch(error){setMessage(error.message||'Import impossible')}finally{setBusy(false)}};
  return <section className="mb-5 rounded-3xl border bg-card p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="flex items-center gap-2 text-lg font-bold"><FileSpreadsheet/>Importer des traiteurs</h2><p className="mt-1 text-sm text-muted-foreground">CSV ou Excel. Colonnes obligatoires : business_name et city.</p><input type="file" accept=".csv,.xls,.xlsx" onChange={event=>setFile(event.target.files?.[0]||null)} className="mt-3 block text-sm"/></div><button type="button" onClick={run} disabled={!file||busy} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground disabled:opacity-50"><Upload size={18}/>{busy?'Import en cours…':'Importer'}</button></div>{message&&<p className="mt-3 rounded-xl bg-secondary p-3 text-sm">{message}</p>}</section>;
}