import { useMemo, useState } from 'react';
import { ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import AdminCatererEditor from '@/components/admin/AdminCatererEditor';
import ProAccountActions from '@/components/admin/ProAccountActions';
import CatererFilters from '@/components/admin/CatererFilters';

export default function CatererTable({items,users,onUpdate,onValidate,onUpdateUser,onDelete}){
  const [filters,setFilters]=useState({search:'',status:'all',plan:'all'});
  const rows=useMemo(()=>items.map(item=>({item,user:item.profile_origin==='owner'?users.find(user=>user.id===item.created_by_id)||null:null})).filter(({item,user})=>{const query=filters.search.trim().toLowerCase();const matchesSearch=!query||`${item.business_name||''} ${item.city||''} ${user?.email||''}`.toLowerCase().includes(query);const matchesStatus=filters.status==='all'||item.status===filters.status;const matchesPlan=filters.plan==='all'||(user?.subscription_plan||'none')===filters.plan;return matchesSearch&&matchesStatus&&matchesPlan}),[items,users,filters]);
  return <section className="overflow-hidden rounded-3xl border bg-card/90 shadow-xl backdrop-blur-xl"><div className="border-b p-5"><h2 className="text-xl font-bold">Professionnels et abonnements</h2><p className="mt-1 text-sm text-muted-foreground">Modifier les fiches, gérer les abonnements et les accès professionnels.</p></div><CatererFilters filters={filters} onChange={setFilters} resultCount={rows.length}/><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr><th className="p-4">Établissement</th><th className="p-4">Ville</th><th className="p-4">Statut</th><th className="p-4">Compte et abonnement</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{rows.map(({item:x,user})=><tr key={x.id} className="border-t align-top"><td className="p-4 font-semibold">{x.business_name}{x.claim_source_profile_id&&<span className="ml-2 rounded-full bg-chart-4/30 px-2 py-1 text-xs text-primary">Revendication à valider</span>}{x.profile_origin==='public_source'&&x.claim_status==='pending'&&<span className="ml-2 rounded-full bg-secondary px-2 py-1 text-xs text-primary">Revendication en cours</span>}<span className="block text-xs font-normal text-muted-foreground">{user?.email}</span></td><td className="p-4">{x.city}</td><td className="p-4"><span className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold">{x.status}</span></td><td className="p-4"><ProAccountActions user={user} onUpdate={onUpdateUser}/></td><td className="p-4"><div className="flex flex-wrap justify-end gap-2">{x.profile_origin==='owner'&&<button onClick={()=>onValidate(x)} className="rounded-lg bg-primary px-3 py-2 text-primary-foreground">Valider</button>}<button onClick={()=>onUpdate(x.id,{status:'changes_requested',published:false})} className="rounded-lg border px-3 py-2">À vérifier</button><button onClick={()=>onUpdate(x.id,{status:'suspended',published:false})} className="rounded-lg border px-3 py-2">Suspendre</button><AdminCatererEditor item={x} onSave={onUpdate}/><Link to={`/traiteurs/${x.slug}`} className="rounded-lg border p-2" aria-label="Voir la fiche"><ExternalLink size={17}/></Link><button onClick={()=>onDelete(x)} className="rounded-lg bg-destructive px-3 py-2 text-destructive-foreground">Supprimer</button></div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-center text-muted-foreground">Aucun traiteur ne correspond à ces filtres.</p>}</div></section>;
}