import { useEffect, useState } from 'react';

function PlanRow({ plan, onSave }) {
  const [form, setForm] = useState(plan);
  const [saving, setSaving] = useState(false);
  useEffect(() => setForm(plan), [plan]);
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); await onSave(plan.id, { name: form.name, description: form.description, monthly_price_ex_vat: Number(form.monthly_price_ex_vat), annual_price_ex_vat: Number(form.annual_price_ex_vat || 0), vat_rate: Number(form.vat_rate || 20), trial_days: Number(form.trial_days || 0), active: !!form.active, highlighted: !!form.highlighted }); setSaving(false); };
  return <article className="rounded-3xl border bg-card/90 p-5 shadow-xl backdrop-blur-xl"><div className="flex items-center justify-between gap-3"><input value={form.name || ''} onChange={e => set('name', e.target.value)} className="h-10 min-w-0 flex-1 rounded-lg border bg-background px-3 font-bold"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.active} onChange={e => set('active', e.target.checked)}/>Active</label></div><textarea value={form.description || ''} onChange={e => set('description', e.target.value)} rows="2" className="mt-3 w-full rounded-lg border bg-background p-3 text-sm" placeholder="Description de l’offre"/><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Mensuel HT (€)<input type="number" min="0" value={form.monthly_price_ex_vat ?? ''} onChange={e => set('monthly_price_ex_vat', e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3"/></label><label className="text-xs font-semibold">Annuel HT (€)<input type="number" min="0" value={form.annual_price_ex_vat ?? ''} onChange={e => set('annual_price_ex_vat', e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3"/></label><label className="text-xs font-semibold">TVA (%)<input type="number" min="0" value={form.vat_rate ?? 20} onChange={e => set('vat_rate', e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3"/></label><label className="text-xs font-semibold">Essai (jours)<input type="number" min="0" value={form.trial_days ?? 0} onChange={e => set('trial_days', e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3"/></label></div><div className="mt-4 flex items-center justify-between"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.highlighted} onChange={e => set('highlighted', e.target.checked)}/>Mettre en avant</label><button type="button" disabled={saving} onClick={save} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60">{saving ? 'Enregistrement…' : 'Enregistrer'}</button></div></article>;
}

export default function PlanTable({ items, onUpdate }) { return <section><div className="mb-5"><h2 className="text-xl font-bold">Abonnements et tarifs</h2><p className="mt-1 text-sm text-muted-foreground">Modifier les offres professionnelles affichées par la plateforme.</p></div><div className="grid gap-4 lg:grid-cols-3">{items.map(plan => <PlanRow key={plan.id} plan={plan} onSave={onUpdate}/>)}</div>{!items.length && <div className="rounded-2xl border bg-card p-6 text-center text-muted-foreground">Aucune offre configurée.</div>}</section>; }