import {useState} from 'react';
import {base44} from '@/api/base44Client';
import {CalendarDays,Clock3,Euro,Eye,LockKeyhole,MapPin,MessageSquare,Send,Utensils,Users} from 'lucide-react';

export default function OpportunityCard({item,subscribed}){
  const[open,setOpen]=useState(false);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[counts,setCounts]=useState({views:item.view_count||0,responses:item.response_count||0});
  const toggle=async()=>{if(!open){const response=await base44.functions.invoke('proOpportunityFeed',{action:'view',kind:item.kind,request_id:item.id});setCounts({views:response.data.view_count,responses:response.data.response_count})}setOpen(x=>!x)};
  const respond=async e=>{e.preventDefault();setBusy(true);setError('');try{const response=await base44.functions.invoke('proOpportunityFeed',{action:'respond',kind:item.kind,request_id:item.id,message});setCounts({views:response.data.view_count,responses:response.data.response_count});setMessage('');window.location.href=`mailto:${item.email}?subject=${encodeURIComponent(`Réponse à votre demande ${item.reference}`)}&body=${encodeURIComponent(message)}`}catch(err){setError(err.response?.data?.error||err.message)}finally{setBusy(false)}};
  return <article className="rounded-2xl border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className={`text-xs font-bold uppercase tracking-wider ${item.kind==='urgent'?'text-destructive':'text-primary'}`}>{item.kind==='urgent'?'Urgence':'Devis classique'}</p><h2 className="mt-1 font-bold">{item.event_type}</h2></div><span className="rounded-full bg-secondary px-2 py-1 text-xs font-bold text-primary">{item.reference}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-muted-foreground"><span className="flex gap-1"><CalendarDays size={14}/>{item.event_date}</span>{item.event_time&&<span className="flex gap-1"><Clock3 size={14}/>{item.event_time}</span>}<span className="flex gap-1"><MapPin size={14}/>{item.location}</span><span className="flex gap-1"><Users size={14}/>{item.guest_count} invités</span>{item.format&&<span className="flex gap-1"><Utensils size={14}/>{item.format}</span>}{item.budget&&<span className="flex gap-1"><Euro size={14}/>{item.budget} €</span>}</div><div className="mt-3 flex gap-4 text-xs font-bold text-muted-foreground"><span className="flex items-center gap-1"><Eye size={14}/>{counts.views} vue(s)</span><span className="flex items-center gap-1"><MessageSquare size={14}/>{counts.responses} réponse(s)</span></div><button type="button" onClick={toggle} className="mt-3 rounded-lg border px-3 py-2 text-xs font-bold">{open?'Fermer':'Voir et répondre'}</button>{open&&(subscribed?<div className="mt-3 border-t pt-3 text-sm"><p className="whitespace-pre-wrap">{item.message||item.service_need||'Aucune précision supplémentaire.'}</p><p className="mt-2 font-semibold">{item.first_name} {item.last_name}</p><a href={`mailto:${item.email}`} className="text-primary underline">{item.email}</a>{item.phone&&<a href={`tel:${item.phone}`} className="ml-3 text-primary underline">{item.phone}</a>}<form onSubmit={respond} className="mt-3"><textarea required minLength={10} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Votre réponse à cette demande…" className="min-h-24 w-full rounded-xl border bg-background p-3"/>{error&&<p className="mt-1 text-xs text-destructive">{error}</p>}<button disabled={busy} className="mt-2 flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground disabled:opacity-50"><Send size={14}/>{busy?'Envoi…':'Envoyer ma réponse'}</button></form></div>:<p className="mt-3 flex gap-2 rounded-xl bg-muted p-3 text-sm"><LockKeyhole size={16}/>Contact et réponse disponibles avec un abonnement actif.</p>)}</article>;
}