import {useEffect,useState} from 'react';
import {CheckCheck,Send} from 'lucide-react';
import {base44} from '@/api/base44Client';

export default function QuoteInlineMessenger({quote,onReplied}){
  const[state,setState]=useState({loading:true,activities:[]});const[text,setText]=useState('');const[busy,setBusy]=useState(false);
  const load=()=>base44.functions.invoke('quoteConversation',{action:'history',quote_id:quote.id}).then(response=>setState({loading:false,...response.data}));
  useEffect(()=>{setState({loading:true,activities:[]});load()},[quote.id]);
  const send=async()=>{setBusy(true);const response=await base44.functions.invoke('quoteConversation',{action:'message',quote_id:quote.id,message:text});setState({loading:false,...response.data});setText('');onReplied?.(quote.id);setBusy(false)};
  const messages=(state.activities||[]).filter(item=>item.type==='message').reverse();
  if(state.loading)return <div className="h-64 animate-pulse rounded-2xl bg-muted"/>;
  return <div className="flex h-full min-h-[520px] flex-col"><header className="border-b pb-4"><p className="text-xs font-bold uppercase tracking-widest text-destructive">Demande de devis · {quote.reference}</p><h3 className="mt-1 text-xl font-bold">{[quote.first_name,quote.last_name].filter(Boolean).join(' ')||'Client'}</h3><p className="text-sm text-muted-foreground">{quote.event_type} · {quote.event_date} · {quote.location}</p></header><div className="flex-1 space-y-3 overflow-y-auto py-4">{messages.length?messages.map(item=><div key={item.id} className={`max-w-[85%] rounded-2xl p-3 text-sm ${item.actor==='professional'?'ml-auto bg-primary text-primary-foreground':'bg-muted'}`}><p>{item.details}</p><small className="mt-1 flex items-center gap-1 opacity-70">{new Date(item.created_date).toLocaleString('fr-FR')}{item.actor==='professional'&&item.read_at&&<><CheckCheck size={13}/>Lu</>}</small></div>):<p className="rounded-2xl bg-muted p-4 text-sm text-muted-foreground">Aucun message dans ce devis.</p>}</div><div className="border-t pt-4"><textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Répondre au client…" className="min-h-24 w-full rounded-xl border bg-background p-3"/><button onClick={send} disabled={busy||!text.trim()} className="mt-2 flex items-center gap-2 rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground disabled:opacity-40"><Send size={16}/>{busy?'Envoi…':'Envoyer'}</button></div></div>;
}