import {useState} from 'react';
import {base44} from '@/api/base44Client';
import QuoteKanbanCard from '@/components/pro/QuoteKanbanCard';

const lanes=[['submitted','Nouveaux'],['matched','À traiter'],['responses_received','En discussion'],['closed','Acceptés'],['cancelled','Refusés']];
export default function QuoteKanbanBoard({items,onOpen,onChanged}){
  const[dragged,setDragged]=useState(null);const[over,setOver]=useState('');
  const drop=async status=>{if(!dragged||dragged.status===status){setDragged(null);setOver('');return;}const previous=dragged;onChanged({...dragged,status});setDragged(null);setOver('');try{const response=await base44.functions.invoke('quoteConversation',{action:'status',quote_id:previous.id,status});onChanged(response.data.item)}catch{onChanged(previous)}};
  return <div className="overflow-x-auto pb-3"><p className="mb-3 text-xs text-muted-foreground">Glissez une carte vers une colonne pour changer son statut.</p><div className="grid min-w-[1180px] grid-cols-5 gap-4">{lanes.map(([status,label])=>{const entries=items.filter(item=>item.status===status||(status==='submitted'&&item.status==='draft'));return <section key={status} onDragOver={event=>{event.preventDefault();setOver(status)}} onDragLeave={()=>setOver('')} onDrop={()=>drop(status)} className={`rounded-2xl border p-3 ${over===status?'border-primary bg-primary/10':'bg-secondary/30'}`}><header className="mb-3 flex items-center justify-between"><h3 className="font-bold">{label}</h3><span className="rounded-full bg-card px-2.5 py-1 text-xs font-bold">{entries.length}</span></header><div className="space-y-3">{entries.map(item=><div key={item.id} draggable onDragStart={()=>setDragged(item)} onDragEnd={()=>{setDragged(null);setOver('')}} className="cursor-grab active:cursor-grabbing"><QuoteKanbanCard item={item} onOpen={onOpen} onChanged={onChanged}/></div>)}{!entries.length&&<p className="rounded-xl border border-dashed bg-card/60 p-4 text-center text-xs text-muted-foreground">Déposez un devis ici</p>}</div></section>})}</div></div>;
}