import { Search, Sparkles } from 'lucide-react';

const toList = value => value.split(',').map(item => item.trim()).filter(Boolean);

export default function SeoFields({ data, setValue }) {
  const title = data.seo_title || `${data.business_name || 'Votre établissement'} — Traiteur à ${data.city || 'votre ville'}`;
  const description = data.seo_description || data.description || 'Ajoutez une description destinée aux moteurs de recherche.';
  const completed = [data.seo_title, data.seo_description, data.geo_summary, data.service_areas?.length, data.seo_keywords?.length].filter(Boolean).length;
  return <section className="rounded-3xl border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-bold text-destructive"><Sparkles size={16}/>SEO & visibilité locale</p><h2 className="mt-1 font-heading text-2xl font-bold">Référencement de votre fiche</h2><p className="mt-2 text-sm text-muted-foreground">Ces informations aident Google et les assistants IA à comprendre votre activité et vos zones d’intervention.</p></div><span className="shrink-0 rounded-full bg-secondary px-3 py-1 text-xs font-bold text-primary">{completed}/5 complété</span></div><div className="mt-6 grid gap-4"><label className="text-sm font-semibold">Titre SEO<input value={data.seo_title || ''} onChange={e=>setValue('seo_title',e.target.value)} maxLength={65} placeholder={title} className="mt-2 w-full rounded-xl border bg-background px-4 py-3 font-normal"/><span className="mt-1 block text-xs font-normal text-muted-foreground">65 caractères maximum · {data.seo_title?.length || 0}/65</span></label><label className="text-sm font-semibold">Description SEO<textarea value={data.seo_description || ''} onChange={e=>setValue('seo_description',e.target.value)} maxLength={160} rows={3} placeholder={description} className="mt-2 w-full rounded-xl border bg-background px-4 py-3 font-normal"/><span className="mt-1 block text-xs font-normal text-muted-foreground">160 caractères maximum · {data.seo_description?.length || 0}/160</span></label><label className="text-sm font-semibold">Résumé GEO pour les assistants IA<textarea value={data.geo_summary || ''} onChange={e=>setValue('geo_summary',e.target.value)} rows={4} placeholder="Décrivez clairement vos spécialités, les événements servis et votre zone d’intervention." className="mt-2 w-full rounded-xl border bg-background px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Villes et zones desservies<input value={(data.service_areas || []).join(', ')} onChange={e=>setValue('service_areas',toList(e.target.value))} placeholder="Lyon, Villeurbanne, Rhône" className="mt-2 w-full rounded-xl border bg-background px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Mots-clés principaux<input value={(data.seo_keywords || []).join(', ')} onChange={e=>setValue('seo_keywords',toList(e.target.value))} placeholder="traiteur mariage, buffet entreprise, cocktail" className="mt-2 w-full rounded-xl border bg-background px-4 py-3 font-normal"/></label></div><div className="mt-6 rounded-2xl border bg-background p-4"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-primary"><Search size={14}/>Aperçu Google</p><p className="mt-3 truncate text-lg text-primary">{title}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></section>;
}