import { Euro } from 'lucide-react';
import { CATERER_SERVICE_OPTIONS } from '@/lib/catererServiceOptions';

export default function ServicePricingFields({data,setValue}) {
  const selected=data.services||[];
  const pricing=data.service_pricing||[];
  const toggle=name=>{const active=selected.includes(name);setValue('services',active?selected.filter(item=>item!==name):[...selected,name]);setValue('service_pricing',active?pricing.filter(item=>item.name!==name):[...pricing.filter(item=>item.name!==name),{name,status:'on_request'}])};
  const update=(name,key,value)=>{const current=pricing.find(item=>item.name===name)||{name,status:'on_request'};setValue('service_pricing',[...pricing.filter(item=>item.name!==name),{...current,[key]:value}])};
  return <section className="rounded-3xl border bg-card/90 p-6 shadow-xl backdrop-blur-xl"><div><p className="text-xs font-bold uppercase tracking-widest text-destructive">Options de prestation</p><h2 className="mt-1 font-heading text-xl font-bold">Services complémentaires</h2><p className="mt-1 text-sm text-muted-foreground">Cochez vos services puis indiquez s’ils sont inclus, sur demande ou proposés à prix fixe.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{CATERER_SERVICE_OPTIONS.map(({name,Icon})=>{const active=selected.includes(name);const item=pricing.find(entry=>entry.name===name)||{status:'on_request'};return <div key={name} className={`rounded-2xl border p-4 ${active?'border-primary/30 bg-primary/5':'bg-background/60'}`}><label className="flex cursor-pointer items-center gap-3 font-bold"><input type="checkbox" checked={active} onChange={()=>toggle(name)} className="h-4 w-4"/><span className="grid h-9 w-9 place-items-center rounded-xl bg-secondary text-primary"><Icon size={18}/></span><span className="text-sm">{name}</span></label>{active&&<div className="mt-3 grid gap-2 sm:grid-cols-2"><select value={item.status||'on_request'} onChange={event=>update(name,'status',event.target.value)} className="h-10 rounded-xl border bg-background px-3 text-sm"><option value="included">Inclus</option><option value="on_request">Sur demande</option><option value="fixed">Prix fixe</option></select>{item.status==='fixed'&&<label className="relative"><Euro size={15} className="absolute left-3 top-3 text-muted-foreground"/><input type="number" min="0" step="0.01" value={item.price??''} onChange={event=>update(name,'price',event.target.value)} className="h-10 w-full rounded-xl border bg-background pl-9 pr-3 text-sm" placeholder="Prix"/></label>}</div>}</div>})}</div></section>;
}