import {useEffect,useMemo,useState} from 'react';
import {BriefcaseBusiness,MessageSquareText,Users} from 'lucide-react';
import {base44} from '@/api/base44Client';
import BookingMessenger from '@/components/extras/BookingMessenger';
import QuoteInlineMessenger from '@/components/pro/QuoteInlineMessenger';

export default function UnifiedProMessaging({quotes=[],quoteMessages=[],bookings=[]}){
  const[channel,setChannel]=useState('quotes');const[selectedId,setSelectedId]=useState('');const[messages,setMessages]=useState([]);const[resolvedQuoteIds,setResolvedQuoteIds]=useState([]);
  useEffect(()=>{let unsubscribe;let userId;base44.auth.me().then(user=>{userId=user.id;return base44.entities.ExtraBookingMessage.filter({members:user.id},'-created_date',500)}).then(items=>setMessages(items)).then(()=>{unsubscribe=base44.entities.ExtraBookingMessage.subscribe(event=>{if(!event.data?.members?.includes(userId))return;setMessages(current=>event.type==='create'?[event.data,...current]:current)})});return()=>unsubscribe?.()},[]);
  const quoteRows=useMemo(()=>quoteMessages.filter(message=>!resolvedQuoteIds.includes(message.quote_id)).map(message=>({...quotes.find(quote=>quote.id===message.quote_id),lastMessage:message})).filter(item=>item.id),[quotes,quoteMessages,resolvedQuoteIds]);
  const extraRows=useMemo(()=>bookings.map(booking=>{const related=messages.filter(item=>item.booking_id===booking.id);return{...booking,lastMessage:related[0]}}).filter(item=>item.lastMessage?.sender_role==='extra').sort((a,b)=>String(b.lastMessage.created_date).localeCompare(String(a.lastMessage.created_date))),[bookings,messages]);
  const rows=channel==='quotes'?quoteRows:extraRows;const selected=rows.find(item=>item.id===selectedId)||rows[0];
  return <section className="mt-6 overflow-hidden rounded-3xl border bg-card shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><p className="text-sm font-bold uppercase tracking-widest text-destructive">Messagerie traiteur</p><h2 className="text-xl font-bold">Toutes vos conversations</h2></div><div className="flex rounded-xl bg-muted p-1"><button onClick={()=>{setChannel('quotes');setSelectedId('')}} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${channel==='quotes'?'bg-card text-primary shadow-sm':'text-muted-foreground'}`}><BriefcaseBusiness size={16}/>Devis ({quoteRows.length})</button><button onClick={()=>{setChannel('extras');setSelectedId('')}} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${channel==='extras'?'bg-card text-primary shadow-sm':'text-muted-foreground'}`}><Users size={16}/>Extras ({extraRows.length})</button></div></header><div className="grid min-h-[620px] lg:grid-cols-[320px_1fr]"><aside className="border-b bg-muted/30 p-3 lg:border-b-0 lg:border-r">{rows.length?rows.map(item=>{const active=item.id===selected?.id;const title=channel==='quotes'?([item.first_name,item.last_name].filter(Boolean).join(' ')||'Client'):(item.extra_name||'Extra');const preview=item.lastMessage?.details||item.lastMessage?.message;return <button key={item.id} onClick={()=>setSelectedId(item.id)} className={`mb-2 w-full rounded-2xl border p-3 text-left ${active?'border-primary bg-card shadow-sm':'border-transparent hover:bg-card'}`}><div className="flex items-center gap-2 font-bold text-primary"><MessageSquareText size={16}/><span className="truncate">{title}</span></div><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{preview}</p><small className="mt-2 block text-muted-foreground">{channel==='quotes'?item.reference:new Date(item.lastMessage.created_date).toLocaleString('fr-FR')}</small></button>}):<p className="rounded-2xl bg-card p-4 text-sm text-muted-foreground">Aucune conversation {channel==='quotes'?'de devis':'avec un Extra'}.</p>}</aside><div className="p-5">{selected?(channel==='quotes'?<QuoteInlineMessenger quote={selected} onReplied={id=>setResolvedQuoteIds(current=>[...current,id])}/>:<><header className="border-b pb-3"><p className="text-xs font-bold uppercase tracking-widest text-destructive">Messagerie interne Extra</p><h3 className="text-xl font-bold">{selected.extra_name}</h3><p className="text-sm text-muted-foreground">Mission du {new Date(`${selected.booking_date}T12:00:00`).toLocaleDateString('fr-FR')} · {selected.service_details}</p></header><BookingMessenger booking={selected} viewerRole="caterer"/></>):<div className="grid min-h-[420px] place-items-center text-center text-muted-foreground"><div><MessageSquareText className="mx-auto mb-3"/><p>Sélectionnez une conversation.</p></div></div>}</div></div></section>;
}