import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BadgeCheck,MessageCircle,Phone} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {useAuth} from '@/lib/AuthContext';
const whatsappNumber=value=>{const digits=String(value||'').replace(/\D/g,'');return digits.startsWith('0')?`33${digits.slice(1)}`:digits};
export default function CatererQuickActions({item}){
  const{isAuthenticated}=useAuth();const[busy,setBusy]=useState(false);const[error,setError]=useState('');const started=useRef(false);const number=whatsappNumber(item.whatsapp_phone);
  const completeClaim=async()=>{if(started.current)return;started.current=true;setBusy(true);setError('');try{await base44.functions.invoke('claimCaterer',{action:'claim',profile_id:item.id});window.location.href='/profil-traiteur'}catch(err){started.current=false;setError(err.response?.data?.error||err.message||'Revendication impossible')}finally{setBusy(false)}};
  const claim=()=>{if(!isAuthenticated){const next=`${window.location.pathname}?claim=1`;window.location.href=`/login?next=${encodeURIComponent(next)}`;return}completeClaim()};
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const resumes=params.get('claim')==='1'||params.get('is_new_user')==='true';if(isAuthenticated&&resumes&&item.profile_origin==='public_source'&&item.claim_status==='unclaimed')completeClaim()},[isAuthenticated,item.id]);
  return <div className="flex w-full flex-col gap-2 md:w-auto md:shrink-0 md:self-end"><div className="flex items-center gap-2"><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('quote:open'))} className="flex flex-1 items-center justify-center gap-2 rounded-full bg-destructive px-6 py-3 font-bold text-destructive-foreground shadow-lg">Obtenir un devis<ArrowRight size={18}/></button>{item.phone&&<a href={`tel:${item.phone}`} aria-label={`Appeler ${item.business_name}`} className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-primary-foreground text-primary shadow-lg"><Phone size={19}/></a>}{number&&<a href={`https://wa.me/${number}?text=${encodeURIComponent(`Bonjour ${item.business_name}, je vous contacte depuis Un Bon Traiteur.`)}`} target="_blank" rel="noreferrer" aria-label={`Contacter ${item.business_name} sur WhatsApp`} className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-chart-2 text-primary-foreground shadow-lg"><MessageCircle size={19}/></a>}</div>{item.profile_origin==='public_source'&&item.claim_status==='unclaimed'&&<button type="button" onClick={claim} disabled={busy} className="flex items-center justify-center gap-2 rounded-full border border-primary-foreground/40 bg-foreground/40 px-4 py-2 text-sm font-bold"><BadgeCheck size={17}/>{busy?'Préparation…':'Revendiquer cette fiche'}</button>}{error&&<small className="rounded-lg bg-destructive px-3 py-2 text-destructive-foreground">{error}</small>}</div>;
}