import { ChefHat, Sparkles } from 'lucide-react';

const price = value => new Intl.NumberFormat('fr-FR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value));

export default function CatererPricingCard({ caterer }) {
  const pricing = caterer.format_pricing || [];
  const items = (caterer.formats || []).map(name => pricing.find(item => item.name === name) || { name });
  if (!items.length) return null;
  return <section className="relative overflow-hidden rounded-[2rem] border bg-card/80 p-5 shadow-xl backdrop-blur-2xl"><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-chart-4/30 blur-2xl"/><div className="relative"><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg"><Sparkles size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-widest text-destructive">Prix / personne</p><h2 className="font-heading text-lg font-bold">Restauration & conditions</h2></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{items.map(item => <div key={item.name} className="flex items-center gap-3 rounded-2xl border border-primary/15 bg-primary/5 p-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-background text-primary shadow-sm"><ChefHat size={17}/></span><div className="min-w-0"><strong className="block truncate text-sm text-primary">{item.name}</strong>{(item.min_guests || item.max_guests) && <span className="text-xs text-muted-foreground">{item.min_guests || '—'} à {item.max_guests || '—'} pers.</span>}</div><span className="ml-auto shrink-0 rounded-full bg-primary px-3 py-2 text-xs font-black text-primary-foreground shadow-md">{item.price_from != null && item.price_from !== '' ? `dès ${price(item.price_from)} €` : 'Sur demande'}</span></div>)}</div><p className="mt-3 text-xs text-muted-foreground">Tarifs indicatifs · devis personnalisé selon l’événement.</p></div></section>;
}