import {useState} from 'react';
import {ArrowRight,BadgeCheck,MessageCircle} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {useAuth} from '@/lib/AuthContext';
const whatsappNumber=value=>{const digits=String(value||'').replace(/\D/g,'');return digits.startsWith('0')?`33${digits.slice(1)}`:digits};
export default function CatererQuickActions({item}){
  const{isAuthenticated}=useAuth();const[busy,setBusy]=useState(false);const[error,setError]=useState('');const number=whatsappNumber(item.whatsapp_phone);
  const claim=async()=>{if(!isAuthenticated){window.location.href=`/login?next=${encodeURIComponent(window.location.pathname)}`;return}setBusy(true);setError('');try{await base44.functions.invoke('claimCaterer',{action:'claim',profile_id:item.id});window.location.href='/profil-traiteur'}catch(err){setError(err.response?.data?.error||err.message)}finally{setBusy(false)}};
  return <div className="flex w-full flex-col gap-2 md:w-auto md:shrink-0 md:self-end">{number&&<a href={`https://wa.me/${number}?text=${encodeURIComponent(`Bonjour ${item.business_name}, je vous contacte depuis Un Bon Traiteur.`)}`} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-full bg-chart-2 px-6 py-3 font-bold text-primary-foreground"><MessageCircle size={18}/>WhatsApp</a>}<button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('quote:open'))} className="flex items-center justify-center gap-2 rounded-full bg-destructive px-6 py-3 font-bold text-destructive-foreground shadow-lg">Obtenir un devis<ArrowRight size={18}/></button>{item.profile_origin==='public_source'&&item.claim_status!=='claimed'&&(item.claim_status==='pending'?<span className="rounded-full bg-background/90 px-4 py-2 text-center text-xs font-bold text-foreground">Revendication en cours de validation</span>:<button type="button" onClick={claim} disabled={busy} className="flex items-center justify-center gap-2 rounded-full border border-primary-foreground/40 bg-foreground/40 px-4 py-2 text-sm font-bold"><BadgeCheck size={17}/>{busy?'Préparation…':'Revendiquer cette fiche'}</button>)}{error&&<small className="rounded-lg bg-destructive px-3 py-2 text-destructive-foreground">{error}</small>}</div>;
}