import {useEffect,useState} from 'react';
import {ArrowLeft, ArrowRight, CheckCircle2, ClipboardList, MapPin} from 'lucide-react';
import {base44} from '@/api/base44Client';
import DirectQuoteEventFields from '@/components/caterer/DirectQuoteEventFields';
import DirectQuoteAddressFields from '@/components/caterer/DirectQuoteAddressFields';
import DirectQuoteContactFields from '@/components/caterer/DirectQuoteContactFields';

export default function QuoteLeadForm({caterer}) {
  const params=new URLSearchParams(window.location.search);
  const [data,setData]=useState({event_type:params.get('event')||'',format:params.get('format')||'',event_date:params.get('date')||'',event_time:'',guest_count:params.get('guests')||'',budget:'',address:'',postal_code:'',city:params.get('location')||'',first_name:'',last_name:'',email:'',phone:'',message:'',transmission_consent:false,caterer_id:caterer.id});
  const [options,setOptions]=useState({events:[],formats:[]});
  const [busy,setBusy]=useState(false);const[result,setResult]=useState('');const[error,setError]=useState('');const[step,setStep]=useState(1);
  useEffect(()=>{Promise.all([base44.entities.EventType.filter({active:true},'display_order',100),base44.entities.Format.filter({active:true},'display_order',100)]).then(([events,formats])=>setOptions({events:events.map(item=>item.name),formats:formats.map(item=>item.name)}))},[]);
  const set=key=>event=>setData(current=>({...current,[key]:event.target.type==='checkbox'?event.target.checked:event.target.value}));
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const location=[data.address,data.postal_code,data.city].filter(Boolean).join(', ');const response=await base44.functions.invoke('createPublicRequest',{kind:'quote',data:{...data,location,guest_count:Number(data.guest_count),budget:Number(data.budget)||undefined,budget_type:'total'},website:''});setResult(response.data.reference)}catch(err){setError(err.message||'Envoi impossible')}finally{setBusy(false)}};
  const next=()=>{if(!data.event_type||!data.format||!data.event_date||!data.guest_count||!data.message.trim()){setError('Complétez les informations obligatoires avant de continuer.');return}setError('');setStep(2)};
  if(result)return <div className="py-8 text-center"><CheckCircle2 className="mx-auto text-primary" size={42}/><h3 className="mt-3 text-xl font-bold">Demande envoyée</h3><p className="mt-2 text-sm text-muted-foreground">Le traiteur dispose de votre dossier complet · Référence {result}</p></div>;
  const events=options.events.length?options.events:(caterer.event_types||[]);const formats=options.formats.length?options.formats:(caterer.formats||[]);
  return <form onSubmit={submit} className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-widest text-destructive">Devis direct et gratuit</p><h2 className="mt-1 font-heading text-xl font-bold">Votre projet avec {caterer.business_name}</h2></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-secondary/60 p-1.5 text-xs font-bold"><div className={`flex items-center justify-center gap-2 rounded-xl px-2 py-2 ${step===1?'bg-primary text-primary-foreground shadow-sm':'text-muted-foreground'}`}><ClipboardList size={15}/>1. Informations</div><div className={`flex items-center justify-center gap-2 rounded-xl px-2 py-2 ${step===2?'bg-primary text-primary-foreground shadow-sm':'text-muted-foreground'}`}><MapPin size={15}/>2. Coordonnées</div></div>{step===1?<><DirectQuoteEventFields data={data} set={set} events={events} formats={formats}/><label className="block text-sm font-semibold">Votre demande<textarea required maxLength="3000" value={data.message} onChange={set('message')} className="mt-1 min-h-20 w-full rounded-xl border bg-background p-3" placeholder="Menu, contraintes, service, matériel…"/></label>{error&&<p className="text-sm text-destructive">{error}</p>}<button type="button" onClick={next} className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground shadow-lg">Continuer <ArrowRight size={17}/></button></>:<><DirectQuoteAddressFields data={data} set={set}/><DirectQuoteContactFields data={data} set={set}/><label className="flex gap-3 rounded-2xl border bg-secondary/40 p-3 text-xs"><input required type="checkbox" checked={data.transmission_consent} onChange={set('transmission_consent')}/><span>J’autorise la transmission de ces informations à {caterer.business_name} pour établir mon devis.</span></label>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="grid grid-cols-[auto_1fr] gap-2"><button type="button" onClick={()=>setStep(1)} className="rounded-xl border px-4" aria-label="Revenir aux informations"><ArrowLeft size={18}/></button><button disabled={busy} className="rounded-xl bg-destructive px-4 py-3 font-bold text-destructive-foreground shadow-lg disabled:opacity-50">{busy?'Envoi…':'Envoyer ma demande'}</button></div><p className="text-center text-xs text-muted-foreground">Sans engagement · Données transmises uniquement au traiteur</p></>}</form>;
}