import {useEffect,useState} from 'react';
import {Navigate} from 'react-router-dom';
import {base44} from '@/api/base44Client';
import Header from '@/components/site/Header';
import Footer from '@/components/site/Footer';
import {Image} from '@/components/ui/image';
import AccountSidebar from '@/components/account/AccountSidebar';
import AccountHero from '@/components/account/AccountHero';
import AccountStats from '@/components/account/AccountStats';
import AccountRequestFeed from '@/components/account/AccountRequestFeed';
import AccountProfileCard from '@/components/account/AccountProfileCard';
const background='https://media.base44.com/images/public/6a61e06a56bdababd200203a/215de3d85_generated_image.png';
export default function AccountPortal(){const[state,setState]=useState({loading:true,user:null,professional:false,extra:false,quotes:[],urgent:[]});useEffect(()=>{base44.auth.me().then(async user=>{const[profiles,extras,quotes,urgent]=await Promise.all([base44.entities.CatererProfile.filter({created_by_id:user.id},'-created_date',1),base44.entities.ExtraProfile.filter({created_by_id:user.id},'-created_date',1),base44.entities.QuoteRequest.list('-created_date',100),base44.entities.UrgentRequest.list('-created_date',100)]);setState({loading:false,user,professional:profiles.length>0,extra:extras.length>0,quotes,urgent})})},[]);if(state.loading)return <div className="min-h-screen animate-pulse bg-muted"/>;if(state.user?.role==='admin')return <Navigate to="/admin" replace/>;if(state.professional)return <Navigate to="/tableau-de-bord-traiteur" replace/>;if(state.extra)return <Navigate to="/inscription-extra" replace/>;const requests=[...state.quotes.map(item=>({...item,kind:'Devis'})),...state.urgent.map(item=>({...item,kind:'Urgence'}))].sort((a,b)=>new Date(b.created_date)-new Date(a.created_date));return <><Header/><main className="relative min-h-screen overflow-hidden bg-primary px-4 py-8"><Image src={background} alt="Fond abstrait vert et crème" className="absolute inset-0 h-full w-full" fittingType="fill"/><div className="absolute inset-0 bg-primary/35"/><div className="relative mx-auto grid max-w-7xl items-start gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><AccountSidebar user={state.user}/><div className="space-y-5"><AccountHero user={state.user}/><AccountStats requests={requests}/><div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><AccountRequestFeed requests={requests}/><AccountProfileCard user={state.user}/></div></div></div></main><Footer/></>;}