import {useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {CalendarDays,ChevronRight,FileText,MapPin,UsersRound} from 'lucide-react';
import {base44} from '@/api/base44Client';
import Header from '@/components/site/Header';
import Footer from '@/components/site/Footer';
import QuoteConversationDialog from '@/components/quotes/QuoteConversationDialog';

const labels={submitted:'Demande envoyée',matched:'Traiteurs sélectionnés',responses_received:'Réponse reçue',closed:'Devis accepté',cancelled:'Devis refusé'};
export default function ClientQuotes(){const[items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[params,setParams]=useSearchParams();useEffect(()=>{base44.entities.QuoteRequest.list('-last_activity_at',200).then(setItems).finally(()=>setLoading(false))},[]);const selected=items.find(item=>item.id===params.get('quote'));const changed=item=>setItems(current=>current.map(x=>x.id===item.id?item:x));return <><Header/><main className="min-h-screen bg-primary/5 px-4 py-8"><div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-widest text-destructive">Espace particulier</p><h1 className="mt-1 font-heading text-4xl font-bold">Mes devis et réponses</h1><p className="mt-2 text-muted-foreground">Consultez les réponses des traiteurs, échangez avec eux et acceptez ou refusez leurs propositions.</p>{loading?<div className="mt-6 h-52 animate-pulse rounded-3xl bg-muted"/>:<div className="mt-6 grid gap-3">{items.map(item=><button key={item.id} onClick={()=>setParams({quote:item.id})} className="rounded-2xl border bg-card p-5 text-left text-card-foreground shadow-sm"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground"><FileText size={20}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">{item.reference}</p><span className="rounded-full bg-secondary px-3 py-1 text-xs font-bold text-secondary-foreground">{labels[item.status]||item.status}</span></div><h2 className="mt-1 font-bold">{item.event_type}</h2><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1"><CalendarDays size={14}/>{item.event_date}</span><span className="flex items-center gap-1"><MapPin size={14}/>{item.location}</span><span className="flex items-center gap-1"><UsersRound size={14}/>{item.guest_count} invités</span></div></div><ChevronRight className="mt-2 shrink-0" size={19}/></div></button>)}{!items.length&&<div className="rounded-3xl border border-dashed bg-card p-10 text-center"><FileText className="mx-auto text-primary"/><h2 className="mt-3 text-xl font-bold">Aucun devis</h2><p className="mt-1 text-sm text-muted-foreground">Vos demandes et les réponses des traiteurs apparaîtront ici.</p></div>}</div>}</div></main><Footer/>{selected&&<QuoteConversationDialog quote={selected} onClose={()=>setParams({})} onChanged={changed}/>}</>}