import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {base44} from '@/api/base44Client';
import Header from '@/components/site/Header';
import Footer from '@/components/site/Footer';
import ExtraOpportunityCard from '@/components/extras/ExtraOpportunityCard';
import ExtraOpportunityFilters from '@/components/extras/ExtraOpportunityFilters';
import ExtraOpportunityMap from '@/components/extras/ExtraOpportunityMap';
import ExtraOpportunityViewToggle from '@/components/extras/ExtraOpportunityViewToggle';

const initialFilters={city:'',latitude:null,longitude:null,radius_km:25,role:'',date:''};
export default function ExtraOpportunities(){
  const[data,setData]=useState({items:[],city:'',radius_km:25});const[roles,setRoles]=useState([]);const[filters,setFilters]=useState(initialFilters);const[loading,setLoading]=useState(true);const[locating,setLocating]=useState(false);const[error,setError]=useState('');const[mobileView,setMobileView]=useState('grid');
  const load=(search=filters)=>{setLoading(true);setError('');return base44.functions.invoke('extrasHub',{action:'extra_opportunities',...search}).then(r=>{setData(r.data);if(!search.city)setFilters(current=>({...current,city:r.data.city||''}))}).catch(e=>setError(e.response?.data?.error||e.message)).finally(()=>setLoading(false))};
  useEffect(()=>{load(initialFilters);base44.entities.ExtraJobType.filter({active:true},'display_order',100).then(items=>setRoles(items.map(item=>item.name)))},[]);
  const locate=()=>{if(!navigator.geolocation){setError('La géolocalisation n’est pas disponible sur cet appareil.');return}setLocating(true);navigator.geolocation.getCurrentPosition(position=>{const next={...filters,city:'Ma position actuelle',latitude:position.coords.latitude,longitude:position.coords.longitude};setFilters(next);setLocating(false);load(next)},()=>{setError('La géolocalisation n’a pas pu être utilisée.');setLocating(false)})};
  const items=useMemo(()=>data.items.filter(item=>(!filters.role||item.role===filters.role)&&(!filters.date||item.event_date===filters.date)).sort((a,b)=>(a.distance_km??Infinity)-(b.distance_km??Infinity)),[data.items,filters.role,filters.date]);
  const view=async item=>{const r=await base44.functions.invoke('extrasHub',{action:'view_request',request_id:item.id});setData(current=>({...current,items:current.items.map(x=>x.id===item.id?{...x,view_count:r.data.view_count}:x)}));return r.data.view_count};
  const apply=async item=>{await base44.functions.invoke('extrasHub',{action:'apply_to_request',request_id:item.id});setData(current=>({...current,items:current.items.map(x=>x.id===item.id?{...x,application_status:'pending'}:x)}))};
  return <><Header/><main className="min-h-screen bg-primary/5 px-4 py-6"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-widest text-destructive">Espace Extra</p><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="mt-1 font-heading text-2xl font-bold">Annonces autour de moi</h1><p className="mt-1 text-sm text-muted-foreground">{items.length} mission(s) dans un rayon de {data.radius_km} km autour de {data.city||'votre ville'}.</p></div><Link to="/inscription-extra" className="font-bold text-primary">← Mon tableau de bord</Link></div><div className="sticky top-16 z-[900] -mx-4 mt-5 bg-background/95 px-4 py-3 backdrop-blur-xl"><ExtraOpportunityFilters value={filters} onChange={setFilters} onSubmit={()=>load(filters)} locating={locating} onLocate={locate} roles={roles}/></div><div className="mt-4"><ExtraOpportunityViewToggle value={mobileView} onChange={setMobileView}/></div><div className="mt-4 grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_380px]"><div className={mobileView==='map'?'block':'hidden lg:block'}><ExtraOpportunityMap items={items} onView={view} onApply={apply}/></div><aside className={`${mobileView==='grid'?'grid':'hidden lg:grid'} grid-cols-1 gap-3 sm:grid-cols-2 lg:max-h-[calc(100vh-230px)] lg:grid-cols-1 lg:overflow-y-auto lg:pr-1`}>{loading?<div className="h-40 animate-pulse rounded-3xl bg-muted"/>:error?<div className="rounded-2xl border bg-card p-5 text-destructive">{error}</div>:items.length?items.map(item=><ExtraOpportunityCard key={item.id} item={item} onView={view} onApply={apply}/>):<div className="rounded-2xl border bg-card p-6 text-center text-sm text-muted-foreground">Aucune annonce avec ces filtres.</div>}</aside></div></div></main><Footer/></>;
}