import {useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import Header from '@/components/site/Header';
import Footer from '@/components/site/Footer';
import ProCrmNav from '@/components/pro/ProCrmNav';
import CatererProfileForm from '@/components/pro/CatererProfileForm';
import ProPlanChoice from '@/components/pro/ProPlanChoice';

export default function ProProfile(){
  const[profile,setProfile]=useState();const[user,setUser]=useState();const[activity,setActivity]=useState({stats:{},items:[]});const[loading,setLoading]=useState(true);const[saved,setSaved]=useState(false);
  useEffect(()=>{Promise.all([base44.auth.me(),base44.functions.invoke('quoteConversation',{action:'list_professional'})]).then(async([current,response])=>{const items=await base44.entities.CatererProfile.filter({created_by_id:current.id},'-created_date',1);setUser(current);setProfile(items[0]||null);setActivity({stats:response.data.stats||{},items:response.data.items||[]})}).finally(()=>setLoading(false))},[]);
  const claimPending=Boolean(profile?.claim_source_profile_id&&profile.status!=='approved');
  const save=async data=>{if(claimPending&&(!user?.subscription_plan||user.subscription_plan==='none'))throw new Error('Choisissez une formule avant d’envoyer votre fiche.');let payload={...data};if(data.address){const query=[data.address,data.postal_code,data.city].filter(Boolean).join(' ');const response=await fetch(`https://api-adresse.data.gouv.fr/search/?q=${encodeURIComponent(query)}&limit=1`);const result=await response.json();const feature=result.features?.[0];if(!feature)throw new Error('Adresse introuvable.');payload={...payload,longitude:feature.geometry.coordinates[0],latitude:feature.geometry.coordinates[1]}}const updated=await base44.entities.CatererProfile.update(profile.id,payload);setProfile({...profile,...updated,...payload});if(claimPending)setSaved(true)};
  if(loading)return <div className="min-h-screen animate-pulse bg-muted"/>;
  if(!profile)return <><Header/><main className="min-h-screen bg-primary/5 px-4 py-8"><div className="mx-auto max-w-7xl"><ProCrmNav/><section className="mt-7 rounded-3xl border bg-card p-8 text-center"><h1 className="text-2xl font-bold">Créez d’abord votre fiche traiteur</h1><a href="/inscription-traiteur" className="mt-5 inline-flex rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground">Créer ma fiche</a></section></div></main><Footer/></>;
  if(claimPending)return <><Header/><main className="min-h-screen bg-primary/5 px-4 py-8"><div className="mx-auto max-w-4xl"><header className="rounded-3xl border bg-card p-6 shadow-xl"><p className="text-sm font-bold uppercase tracking-widest text-destructive">Revendication de fiche</p><h1 className="mt-2 font-heading text-3xl font-bold">Confirmez vos coordonnées</h1><p className="mt-3 text-muted-foreground">Complétez vos informations et choisissez votre formule. Après envoi, notre équipe vérifiera la fiche avant de débloquer votre espace professionnel.</p></header>{saved&&<p className="mt-5 rounded-2xl border border-primary/20 bg-secondary p-4 font-semibold text-primary">Vos informations ont été envoyées. La fiche est maintenant en attente de vérification.</p>}<div className="mt-6 space-y-6"><ProPlanChoice value={user?.subscription_plan||'none'} onSelected={setUser}/><CatererProfileForm key={profile?.updated_date} initial={profile} onSave={save} submitLabel="Envoyer pour vérification" initialTab="contact" contactOnly/></div></div></main><Footer/></>;
  return <><Header/><main className="min-h-screen bg-primary/5 px-4 py-8"><div className="mx-auto max-w-7xl"><ProCrmNav/><div className="my-7"><p className="text-sm font-bold uppercase tracking-widest text-destructive">Paramètres entreprise</p><h1 className="mt-1 font-heading text-4xl font-bold">Ma fiche traiteur</h1><p className="mt-2 text-muted-foreground">Gérez vos prestations, vos performances SEO et vos coordonnées.</p></div><section className="max-w-5xl rounded-3xl border bg-card p-6 shadow-xl"><CatererProfileForm key={profile?.updated_date} initial={profile} onSave={save} submitLabel="Enregistrer ma fiche" showSeo={profile?.status==='approved'} stats={activity.stats} quoteItems={activity.items}/></section></div></main><Footer/></>;
}