import { Link } from 'react-router-dom';
import { Eye, MessageSquareText, Navigation, Phone, Utensils } from 'lucide-react';
import { Image } from '@/components/ui/image';

const fallback = 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1200&q=85';

export default function CatererMapCard({ item }) {
  const destination = item.address ? `${item.address}, ${item.postal_code || ''} ${item.city}` : `${item.latitude},${item.longitude}`;
  return <article className="w-[min(calc(100vw-3rem),430px)] max-w-full rounded-[1.5rem] bg-primary p-2 shadow-2xl sm:p-3">
    <div className="grid gap-3 md:grid-cols-[0.95fr_1.05fr]">
      <div className="relative h-36 overflow-visible rounded-2xl sm:h-44 sm:rounded-3xl md:h-auto md:min-h-[230px]"><Image src={item.hero_image || fallback} alt={`Buffet de ${item.business_name}`} className="absolute inset-0 h-full w-full rounded-3xl" fittingType="fill"/><div className="absolute -bottom-5 left-4 z-10 grid h-16 w-16 place-items-center overflow-hidden rounded-2xl border border-primary-foreground/40 bg-card/75 p-2 text-primary shadow-2xl backdrop-blur-xl md:-right-8 md:bottom-auto md:left-auto md:top-6 md:h-24 md:w-24 md:rounded-3xl md:p-3">{item.logo_url ? <Image src={item.logo_url} alt={`Logo ${item.business_name}`} className="h-full w-full" fittingType="fit"/> : <Utensils className="h-11 w-11"/>}</div></div>
      <div className="flex min-w-0 flex-col gap-2 pt-6 sm:gap-3 md:pt-0"><div className="rounded-2xl border border-primary-foreground/30 bg-primary-foreground/15 px-4 py-3 shadow-xl backdrop-blur-xl sm:rounded-3xl sm:px-6 sm:py-5"><h3 className="break-words font-heading text-xl font-bold text-primary-foreground sm:text-2xl md:text-3xl">{item.business_name}</h3></div><div className="flex-1 rounded-2xl border border-primary-foreground/30 bg-primary-foreground/15 px-4 py-3 text-sm text-primary-foreground shadow-xl backdrop-blur-xl sm:rounded-3xl sm:px-6 sm:py-5 sm:text-base"><p>{item.address}</p><p>{item.postal_code} · {item.city}</p></div><div className="grid grid-cols-2 gap-2 sm:gap-3"><Link to={`/traiteurs/${item.slug}`} className="caterer-action group flex min-h-14 sm:min-h-16 items-center justify-center gap-2 rounded-3xl border border-primary-foreground/25 bg-primary-foreground/10 px-2 text-center text-xs font-bold sm:px-3 sm:text-sm shadow-xl backdrop-blur-xl transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl active:translate-y-0"><Eye className="h-5 w-5 transition-transform duration-300 group-hover:scale-110"/>Voir la fiche</Link><a href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}`} target="_blank" rel="noreferrer" className="caterer-action group flex min-h-14 sm:min-h-16 items-center justify-center gap-2 rounded-3xl border border-primary-foreground/25 bg-primary-foreground/10 px-2 text-center text-xs font-bold sm:px-3 sm:text-sm shadow-xl backdrop-blur-xl transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl active:translate-y-0"><Navigation className="h-5 w-5 transition-transform duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5"/>M’y rendre</a><a href={`tel:${item.phone}`} className="caterer-action group flex min-h-14 sm:min-h-16 items-center justify-center gap-2 rounded-3xl border border-primary-foreground/25 bg-primary-foreground/10 px-2 text-center text-xs font-bold sm:px-3 sm:text-sm shadow-xl backdrop-blur-xl transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl active:translate-y-0"><Phone className="h-5 w-5 transition-transform duration-300 group-hover:rotate-12 group-hover:scale-110"/>Appeler</a><Link to={`/traiteurs/${item.slug}#devis`} className="caterer-action caterer-action--accent group flex min-h-14 sm:min-h-16 items-center justify-center gap-2 rounded-3xl border border-secondary bg-secondary px-2 text-center text-xs font-bold sm:px-3 sm:text-sm shadow-xl transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl active:translate-y-0"><MessageSquareText className="h-5 w-5 shrink-0 transition-transform duration-300 group-hover:scale-110"/>Demander un devis</Link></div></div>
    </div>
  </article>;
}