import { Link } from 'react-router-dom';
import { Eye, MessageSquareText, Navigation, Phone, Utensils } from 'lucide-react';
import { Image } from '@/components/ui/image';

const fallback = 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1200&q=85';

export default function CatererMapCard({ item }) {
  const destination = item.address ? `${item.address}, ${item.postal_code || ''} ${item.city}` : `${item.latitude},${item.longitude}`;
  return <article className="w-[280px] max-w-full rounded-2xl bg-primary p-2 shadow-xl">
    <div className="relative h-24 overflow-hidden rounded-xl"><Image src={item.hero_image || fallback} alt={`Buffet de ${item.business_name}`} className="h-full w-full" fittingType="fill"/><div className="absolute bottom-2 left-2 grid h-11 w-11 place-items-center overflow-hidden rounded-xl border border-primary-foreground/40 bg-card/90 p-1.5 text-primary">{item.logo_url ? <Image src={item.logo_url} alt={`Logo ${item.business_name}`} className="h-full w-full" fittingType="fit"/> : <Utensils className="h-6 w-6"/>}</div></div>
    <div className="px-1 pb-1 pt-2 text-primary-foreground"><h3 className="truncate font-heading text-base font-bold">{item.business_name}</h3><p className="mt-1 truncate text-xs text-primary-foreground/80">{item.address}</p><p className="truncate text-xs text-primary-foreground/80">{item.postal_code} · {item.city}</p></div>
    <div className="mt-1 grid grid-cols-2 gap-1.5"><Link to={`/traiteurs/${item.slug}`} className="caterer-action flex min-h-9 items-center justify-center gap-1 rounded-xl border border-primary-foreground/25 bg-primary-foreground/10 px-2 text-[11px] font-bold"><Eye className="h-3.5 w-3.5"/>Voir la fiche</Link><a href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}`} target="_blank" rel="noreferrer" className="caterer-action flex min-h-9 items-center justify-center gap-1 rounded-xl border border-primary-foreground/25 bg-primary-foreground/10 px-2 text-[11px] font-bold"><Navigation className="h-3.5 w-3.5"/>Itinéraire</a><a href={`tel:${item.phone}`} className="caterer-action flex min-h-9 items-center justify-center gap-1 rounded-xl border border-primary-foreground/25 bg-primary-foreground/10 px-2 text-[11px] font-bold"><Phone className="h-3.5 w-3.5"/>Appeler</a><Link to={`/traiteurs/${item.slug}#devis`} className="caterer-action caterer-action--accent flex min-h-9 items-center justify-center gap-1 rounded-xl border border-secondary bg-secondary px-2 text-[11px] font-bold"><MessageSquareText className="h-3.5 w-3.5"/>Devis</Link></div>
  </article>;
}